#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CACHE_DIR="${ROOT_DIR}/.asset-cache"
ASSET_DIR="${ROOT_DIR}/app/src/main/assets"
HASH_MANIFEST="${ROOT_DIR}/third_party/paddle-assets.sha256"
NATIVE_DIR="${ROOT_DIR}/app/src/main"
PADDLE_DIR="${NATIVE_DIR}/paddle"
JNICALL_DIR="${NATIVE_DIR}/jniLibs/arm64-v8a"
OPENCV_DIR="${NATIVE_DIR}/opencv"

PADDLE_URL="https://paddlelite-demo.bj.bcebos.com/libs/android/paddle_lite_libs_v2_10_rc.tar.gz"
OPENCV_URL="https://paddlelite-demo.bj.bcebos.com/libs/android/opencv-4.2.0-android-sdk.tar.gz"
OCR_DET_URL="https://paddlelite-demo.bj.bcebos.com/demo/ocr/models/ch_ppocr_mobile_v2.0_det_slim_opt_for_cpu_v2_10_rc.tar.gz"
OCR_CLS_URL="https://paddlelite-demo.bj.bcebos.com/demo/ocr/models/ch_ppocr_mobile_v2.0_cls_slim_opt_for_cpu_v2_10_rc.tar.gz"
OCR_REC_URL="https://paddlelite-demo.bj.bcebos.com/demo/ocr/models/ch_ppocr_mobile_v2.0_rec_slim_opt_for_cpu_v2_10_rc.tar.gz"
OCR_LABELS_URL="https://paddlelite-demo.bj.bcebos.com/demo/ocr/labels/labels.tar.gz"
OCR_IMAGES_URL="https://paddlelite-demo.bj.bcebos.com/demo/ocr/images/images.tar.gz"
OBJECT_URL="https://paddlelite-demo.bj.bcebos.com/demo/object_detection/models/ssd_mobilenet_v1_pascalvoc_for_cpu_v2_10.tar.gz"
OBJECT_IMAGE_URL="https://raw.githubusercontent.com/PaddlePaddle/Paddle-Lite-Demo/develop/object_detection/assets/images/dog.jpg"
FACE_URL="https://paddlelite-demo.bj.bcebos.com/models/facedetection_fp32_240_430_for_cpu_v2_10_rc.tar.gz"
FACE_IMAGE_URL="https://raw.githubusercontent.com/PaddlePaddle/Paddle-Lite-Demo/develop/face_detection/assets/images/face.jpg"

mkdir -p "${CACHE_DIR}" "${ASSET_DIR}" "${PADDLE_DIR}" "${JNICALL_DIR}" "${OPENCV_DIR}"

fetch() {
    local name="$1"
    local url="$2"
    local output="${CACHE_DIR}/${name}"
    if [[ ! -s "${output}" ]]; then
        curl --fail --location --retry 3 --retry-delay 2 --output "${output}.part" "${url}"
        mv "${output}.part" "${output}"
    fi
    printf '%s  %s\n' "$(shasum -a 256 "${output}" | cut -d ' ' -f 1)" "${name}"
}

require_file() {
    local path="$1"
    if [[ ! -s "${path}" ]]; then
        printf 'Required asset is missing or empty: %s\n' "${path}" >&2
        exit 1
    fi
}

write_hash_manifest() {
    {
        printf '# Generated by scripts/fetch_paddle_assets.sh; do not edit manually.\n'
        printf '# Paddle Lite runtime and all packaged model/sample assets use v2.10-rc.\n'
        find "${JNICALL_DIR}" "${ASSET_DIR}" -type f -print0 | sort -z | xargs -0 shasum -a 256
    } > "${HASH_MANIFEST}"
}

extract_one() {
    local archive="$1"
    local destination="$2"
    local staging
    staging="$(mktemp -d)"
    tar -xzf "${archive}" -C "${staging}"
    mkdir -p "${destination}"
    cp -R "${staging}"/. "${destination}"/
    rm -rf "${staging}"
}

fetch paddle-lite-v2.10-rc.tar.gz "${PADDLE_URL}"
fetch opencv-4.2.0-android-sdk.tar.gz "${OPENCV_URL}"
fetch ocr-det-v2.10.tar.gz "${OCR_DET_URL}"
fetch ocr-cls-v2.10.tar.gz "${OCR_CLS_URL}"
fetch ocr-rec-v2.10.tar.gz "${OCR_REC_URL}"
fetch ocr-labels.tar.gz "${OCR_LABELS_URL}"
fetch ocr-images.tar.gz "${OCR_IMAGES_URL}"
fetch ssd-mobilenet-v1-pascalvoc-v2.10.tar.gz "${OBJECT_URL}"
fetch dog.jpg "${OBJECT_IMAGE_URL}"
fetch face-detection-v2.10.tar.gz "${FACE_URL}"
fetch face.jpg "${FACE_IMAGE_URL}"

rm -rf "${PADDLE_DIR}" "${OPENCV_DIR}"
mkdir -p "${PADDLE_DIR}" "${OPENCV_DIR}"
extract_one "${CACHE_DIR}/paddle-lite-v2.10-rc.tar.gz" "${PADDLE_DIR}"
extract_one "${CACHE_DIR}/opencv-4.2.0-android-sdk.tar.gz" "${OPENCV_DIR}"

require_file "${PADDLE_DIR}/java/libs/arm64-v8a/libpaddle_lite_jni.so"
require_file "${PADDLE_DIR}/java/libs/arm64-v8a/libc++_shared.so"
require_file "${OPENCV_DIR}/sdk/native/libs/arm64-v8a/libopencv_java4.so"

# Paddle Lite v2.10's Java API loads libpaddle_lite_jni.so from paddle/java/libs.
# Do not link the legacy C++ runtime from CMake: modern NDK linkers reject its
# malformed local ELF symbols. The C++ headers remain available for later demo adaptation.
rm -f "${JNICALL_DIR}/libpaddle_light_api_shared.so" "${JNICALL_DIR}/libc++_shared.so"
cp "${PADDLE_DIR}/java/libs/arm64-v8a/libpaddle_lite_jni.so" "${JNICALL_DIR}/"
cp "${PADDLE_DIR}/java/libs/arm64-v8a/libc++_shared.so" "${JNICALL_DIR}/"
cp "${OPENCV_DIR}/sdk/native/libs/arm64-v8a/libopencv_java4.so" "${JNICALL_DIR}/"

rm -rf "${ASSET_DIR}/models" "${ASSET_DIR}/dictionaries" "${ASSET_DIR}/samples"
mkdir -p "${ASSET_DIR}/models/ocr" "${ASSET_DIR}/models/object" "${ASSET_DIR}/models/face" "${ASSET_DIR}/dictionaries" "${ASSET_DIR}/samples"

extract_one "${CACHE_DIR}/ocr-det-v2.10.tar.gz" "${ASSET_DIR}/models/ocr"
extract_one "${CACHE_DIR}/ocr-cls-v2.10.tar.gz" "${ASSET_DIR}/models/ocr"
extract_one "${CACHE_DIR}/ocr-rec-v2.10.tar.gz" "${ASSET_DIR}/models/ocr"
extract_one "${CACHE_DIR}/ocr-labels.tar.gz" "${ASSET_DIR}/dictionaries"
extract_one "${CACHE_DIR}/ocr-images.tar.gz" "${ASSET_DIR}/samples/ocr"
extract_one "${CACHE_DIR}/ssd-mobilenet-v1-pascalvoc-v2.10.tar.gz" "${ASSET_DIR}/models/object"
extract_one "${CACHE_DIR}/face-detection-v2.10.tar.gz" "${ASSET_DIR}/models/face"
cp "${CACHE_DIR}/dog.jpg" "${ASSET_DIR}/samples/object_dog.jpg"
cp "${CACHE_DIR}/face.jpg" "${ASSET_DIR}/samples/face.jpg"

require_file "${ASSET_DIR}/models/ocr/ch_ppocr_mobile_v2.0_det_slim_opt.nb"
require_file "${ASSET_DIR}/models/ocr/ch_ppocr_mobile_v2.0_cls_slim_opt.nb"
require_file "${ASSET_DIR}/models/ocr/ch_ppocr_mobile_v2.0_rec_slim_opt.nb"
require_file "${ASSET_DIR}/models/object/ssd_mobilenet_v1_pascalvoc_for_cpu/model.nb"
require_file "${ASSET_DIR}/models/face/model.nb"
require_file "${ASSET_DIR}/samples/object_dog.jpg"
require_file "${ASSET_DIR}/samples/face.jpg"
write_hash_manifest
printf 'Paddle assets are ready. Hash manifest: third_party/paddle-assets.sha256\n'